### ISSUE TITLE
Unable to comment on blog post?

### ISSUE THREAD

**Issue by MatthieuStigler** [PMassicotte/blog#4]
Bonjour Philippe

Thanks for the blog! I wanted to use the comment function in the blog, but got an error message, see below. 

![Screenshot from 2023-06-03 13-40-37](https://github.com/PMassicotte/blog/assets/108840/b3fe02b6-883d-42e5-9e82-5b9e40b72060)

And just as a parenthesis, this is the comment I wanted to make on your post on `renv`:

> Nice! I've often encountered problems with renv on Linux when re-opening old(er) projects. Moving from R 4.2 to 4.3 for example led to more than 10 packages not re-compiling. Unfortunately, for none of these packages did the 'rebuild' option work for the initial version (I had to just update to the latest version with record). 

But hopefully that was a special case (I think 4.3 became stricter with compiled code), and I look forward to testing this approach again in the future. Thanks!

**Comment by PMassicotte** [comment]
Bonjour @MatthieuStigler!

Thank you for the comment problem, I am trying to fix this now! As for compiling packages, it is a nightmare, :) The best solution I found so far was Docker and using RSPM. I am about to write a blog post about the workflow I am using. Stay tuned!

**Comment by PMassicotte** [comment]
Comments are now working. Thanks for pointing it out.

**Comment by MatthieuStigler** [comment]
ca marche, super!

**Comment by PMassicotte** [comment]
Merci à toi!
